# Generated by Django 2.1 on 2019-12-31 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two', '0004_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='c_boy_num',
            field=models.IntegerField(default=10),
        ),
    ]
